name: Project setup
description: Install node, checkout project and install packages
author: "Romuald Oluwatobi <romualdnoualinon@gmail.com>"
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        registry-url: "https://registry.npmjs.org"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packages
      run: npm install
      shell: bash
