name: Test build
run-name: Test build on push to main
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "__tests__/**"

jobs:
  test:
    uses: ./.github/workflows/test-reuse.yml
